
import java.awt.print.PrinterException;
import static java.lang.Class.forName;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sohail
 */
public class market extends javax.swing.JFrame {

    /**
     * Creates new form market
     */
    public market() {
        initComponents();
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        label1.setOpaque(true);
      ta.setText(ta.getText()+"_________________________________"+'\n');
        ta.setText(ta.getText()+"            ***MINI MART****     "+'\n');
        ta.setText(ta.getText()+"            ****RECIEPT****      "+'\n');

    }
    public String items;
    public int prices;
    public int qty;
    public int subtotal;
    public int balance;
    public int itemcode = 1;
    DefaultTableModel model1;
    Connection con;
    PreparedStatement ps;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pan1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        quantity = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        add = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pay = new javax.swing.JTextField();
        invoice = new javax.swing.JButton();
        RECEIPT = new javax.swing.JLabel();
        print = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan1.setBackground(new java.awt.Color(102, 102, 102));
        pan1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  MINI MART");
        pan1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 180, 40));

        jPanel1.add(pan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ITEM NAME :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, 30));

        label1.setBackground(new java.awt.Color(102, 102, 255));
        label1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(204, 0, 0));
        label1.setText("    BILLING");
        label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 150, 40));

        name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 180, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("ITEM PRICE :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 80, 30));
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 40, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("QUANTITY :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 80, 40));
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 180, 40));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM NAME", "QUANTITY", "ITEM CODE", "PRICE"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 470, 190));

        add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add.setText("ADD");
        add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        remove.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        remove.setText("REMOVE");
        remove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        jPanel1.add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("     TOTAL");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 80, 20));

        total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 120, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("PAY");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, -1, -1));

        pay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 120, 30));

        invoice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        invoice.setText("INVOICE");
        invoice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceActionPerformed(evt);
            }
        });
        jPanel1.add(invoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 80, 30));

        RECEIPT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RECEIPT.setText("   RECIEPT");
        jPanel1.add(RECEIPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 110, 30));

        print.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        print.setText("PRINT");
        print.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel1.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, -1, -1));

        ta.setColumns(20);
        ta.setRows(5);
        jScrollPane2.setViewportView(ta);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 230, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        items = name.getText();
        prices = Integer.valueOf(price.getText());
        qty = (int) quantity.getValue();
        
        model1 = (DefaultTableModel)table.getModel();
        model1.addRow(new Object[]{
            items,
            qty,
            itemcode,
            prices,
    });
        itemcode++;
        for(int i =0;i<table.getRowCount();i++){
            subtotal = subtotal + Integer.parseInt(table.getValueAt(i, 3).toString());
            
         
        }
        
        total.setText(Integer.valueOf(subtotal).toString());
       total.setEditable(false);
       
        ta.setText(ta.getText()+"_________________________________"+'\n');
        ta.setText(ta.getText()+"_________________________________"+'\n');
        ta.setText(ta.getText()+"PRODUCTS :"+items+'\n');
        ta.setText(ta.getText()+"PRICE    :"+prices+'\n');
        ta.setText(ta.getText()+"QUANTITY :"+qty+'\n');
        ta.setEditable(false);
       
    }//GEN-LAST:event_addActionPerformed
           int lastid;  
    public void db(){
        
            int sub = Integer.valueOf(total.getText().toString());
            String na = null;
            
            
            
            for(int i= 0; i< table.getRowCount();i++){
                na = (String) model1.getValueAt(i, 0);
              
            }
            
           try{    
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/minimart","root","ahmer1234");
            String query = "insert into sales(id,product,price)values(?,?,?)";
            ps = con.prepareStatement(query,Statement.RETURN_GENERATED_KEYS );
            
            ps.setInt(1 , itemcode);
            ps.setString(2, na);
            ps.setInt(3, sub);
            
            ps.executeUpdate();
            
            ResultSet rs = ps.getGeneratedKeys();
            if(rs.next()){
                rs.getInt(1);
            }
            
            JOptionPane.showMessageDialog(this, "Sales Complete");
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(market.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(market.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         
        
     
     
 }
    
    
    
    
    
    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
        if(table.getSelectedRowCount()>= 1){
        
           
                    model1.removeRow(table.getSelectedRow());
                for(int i =0;i<table.getRowCount();i++){
            subtotal = subtotal + Integer.parseInt(table.getValueAt(i, 3).toString());
            
         
        }
    
                total.setText(Integer.valueOf(subtotal).toString());}
        else{
            JOptionPane.showMessageDialog(this, "Please select a row");
        }
    }//GEN-LAST:event_removeActionPerformed

    private void invoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceActionPerformed
        // TODO add your handling code here:
        db();
    
        
    }//GEN-LAST:event_invoiceActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        try {
            // TODO add your handling code here:
            ta.print();
        } catch (PrinterException ex) {
            Logger.getLogger(market.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(market.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(market.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(market.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(market.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new market().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RECEIPT;
    private javax.swing.JButton add;
    private javax.swing.JButton invoice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label1;
    private javax.swing.JTextField name;
    private javax.swing.JPanel pan1;
    private javax.swing.JTextField pay;
    private javax.swing.JTextField price;
    private javax.swing.JButton print;
    private javax.swing.JSpinner quantity;
    private javax.swing.JButton remove;
    private javax.swing.JTextArea ta;
    private javax.swing.JTable table;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables







}
